#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "fluffychat"
name = "Fluffychat"
description.en = "Matrix messenger client"
description.fr = "Client de messagerie Matrix"

version = "1.19.0~ynh1"

maintainers = [ "OniriCorpe" ]

[upstream]
license = "AGPL-3.0-only"
website = "https://fluffychat.im/"
demo = "https://fluffychat.im/web"
userdoc = "https://github.com/krille-chan/fluffychat/wiki#-user-guides"
code = "https://github.com/krille-chan/fluffychat"
fund = "https://ko-fi.com/krille"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "70M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/fluffychat"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.default_matrix_server]
    ask.en = "Default Matrix server"
    ask.fr = "Serveur Matrix par défaut"
    help.en = "Must be a domain name or a sub-domain. Must not contain a path."
    help.fr = "Doit être un nom de domaine ou un sous-domaine. Ne doit pas contenir de chemin d'accès."
    type = "url"
    default = "https://matrix.org"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/krille-chan/fluffychat/releases/download/v1.19.0/fluffychat-web.tar.gz"
        sha256 = "b5083f9932f711f85d9dd778cec359cb603af375abdc20168fd4504e23b54ae9"
        in_subdir = 2

        autoupdate.asset = "fluffychat-web.tar.gz"
        autoupdate.strategy = "latest_github_release"

[resources.install_dir]
owner = "www-data:rx"
group = "www-data:rx"

[resources.permissions]
main.url = "/"
