#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

install_dir=$(ynh_app_setting_get --key=install_dir)

#=================================================
# SPECIFIC GETTERS
#=================================================

get__default_matrix_server() {

    default_matrix_server=$(ynh_app_setting_get --key=default_matrix_server)

    echo "$default_matrix_server"
}

#=================================================
# SPECIFIC SETTERS
#=================================================

set__default_matrix_server() {

    old_value=${old[default_matrix_server]}

    # patching main.dart.js to replace the default matrix server
    ynh_replace --match="=\"$old_value\"" --replace="=\"$default_matrix_server\"" --file="$install_dir/main.dart.js"

    ynh_app_setting_set --key=default_matrix_server --value="$default_matrix_server"
}

#=================================================
ynh_app_config_run "$1"
