#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

install_dir=$(ynh_app_setting_get --app="$app" --key=install_dir)
default_matrix_server=$(ynh_app_setting_get --app="$app" --key=default_matrix_server)

#=================================================
# SPECIFIC SETTERS
#=================================================

set__default_matrix_server() {

    # patching main.dart.js to replace the default matrix server
    ynh_replace_string --match_string="\$\.cmx=\".*\"" --replace_string="\$\.cmx=\"$default_matrix_server\"" --target_file="$install_dir/main.dart.js"

    ynh_app_setting_set --app="$app" --key=default_matrix_server --value="$default_matrix_server"
}

#=================================================
# GENERIC FINALIZATION
#=================================================
ynh_app_config_run "$1"
